#backend/docker-compose.yml
version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: movie_tracker_db
    restart: always
    environment:
      POSTGRES_DB: movie_tracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d movie_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
